controllers:
    resource:
        path: ../src/Controller/Controller
        namespace: App\Controller\Controller
    type: attribute

admin:
    resource: ../src/Controller/Admin/
    type: attribute