networks:
  traefik:
    external: true
  internal:
    external: false

volumes:
  php_socket:
  caddy_data:
  caddy_config:

services:
  php:
    image: ghcr.io/eventpoints/kerrialnewham.com-php:main
    volumes:
      - php_socket:/var/run/php
      - ./php/php.ini:/usr/local/etc/php/php.ini
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    environment:
      MERCURE_PUBLIC_URL: "https://kerrialnewham.com/.well-known/mercure"
      APP_ENV: "prod"
      DATABASE_URL: "postgresql://__KERRIALNEWHAM_POSTGRES_USER__:__KERRIALNEWHAM_POSTGRES_PASSWORD__@__KERRIALNEWHAM_POSTGRES_HOST__:__KERRIALNEWHAM_POSTGRES_PORT__/__KERRIALNEWHAM_POSTGRES_DBNAME__?sslmode=require"
      APP_SECRET: "__KERRIALNEWHAM_APP_SECRET__"
      MAILER_DSN: "__KERRIALNEWHAM_MAILER_DSN__"
      MESSENGER_TRANSPORT_DSN: "__KERRIALNEWHAM_MESSENGER_TRANSPORT_DSN__"
    networks:
      - internal

  caddy:
    image: ghcr.io/eventpoints/kerrialnewham.com-caddy:main
    depends_on:
      - php
    restart: unless-stopped
    environment:
      SERVER_NAME: ":80"
      MERCURE_PUBLISHER_JWT_KEY: "__KERRIALNEWHAM_MERCURE_JWT_SECRET__"
      MERCURE_SUBSCRIBER_JWT_KEY: "__KERRIALNEWHAM_MERCURE_JWT_SECRET__"
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    expose:
      - "80"
      - "443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kerrialnewham.rule=Host(`kerrialnewham.com`)"
      - "traefik.http.routers.kerrialnewham.tls=true"
      - "traefik.http.routers.kerrialnewham.tls.certresolver=le"
    networks:
      - traefik
      - internal
