networks:
  traefik:
    external: true
  internal:
    external: false

volumes:
  php_socket:
  caddy_data:
  caddy_config:

services:
  php:
    image: ghcr.io/eventpoints/kerrialnewham.com-php:main
    volumes:
      - php_socket:/var/run/php
      - ./php/php.ini:/usr/local/etc/php/php.ini
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    depends_on:
      - database
    restart: unless-stopped
    environment:
      MERCURE_PUBLIC_URL: "https://kerrialnewham.com/.well-known/mercure"
      APP_ENV: "prod"
      DATABASE_URL: "__DATABASE_URL__"
      APP_SECRET: "__APP_SECRET__"
      MAILER_DSN: "__MAILER_DSN__"
      MESSENGER_TRANSPORT_DSN: "__MESSENGER_TRANSPORT_DSN__"
    networks:
      - internal

  caddy:
    image: ghcr.io/eventpoints/kerrialnewham.com-caddy:main
    depends_on:
      - php
    restart: unless-stopped
    environment:
      SERVER_NAME: ":80"
      MERCURE_PUBLISHER_JWT_KEY: "__PINBOARDABLE_MERCURE_JWT_SECRET__"
      MERCURE_SUBSCRIBER_JWT_KEY: "__PINBOARDABLE_MERCURE_JWT_SECRET__"
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kerrialnewham.rule=Host(`kerrialnewham.com`, `www.kerrialnewham.com`)"
      - "traefik.http.routers.kerrialnewham.tls=true"
      - "traefik.http.routers.kerrialnewham.tls.certresolver=le"
    networks:
      - traefik
      - internal

  database:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: "__PINBOARDABLE_POSTGRES_DBNAME__"
      POSTGRES_PASSWORD: "__PINBOARDABLE_POSTGRES_PASSWORD__"
      POSTGRES_USER: "__PINBOARDABLE_POSTGRES_USER__"
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
    networks:
      - internal

  adminer:
    image: adminer:4.8.0
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: database
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kerrialnewham-adminer.rule=Host(`adminer.kerrialnewham.com`)"
      - "traefik.http.routers.kerrialnewham-adminer.tls=true"
      - "traefik.http.routers.kerrialnewham-adminer.tls.certresolver=le"
    networks:
      - internal
      - traefik
